### ISSUE TITLE
Error when trying to run a fresh react-kit

### ISSUE THREAD

**Issue by proofoftom** [aragon/aragon-react-kit-boilerplate#19]
```
 ~/code/aragon/app $ node -v
v10.14.1

 ~/code/aragon/app $ aragon -v
5.2.1

 ~/code/aragon $ aragon init app react-kit
 ✔ Preparing initialization
 ✔ Cloning app template
 ✔ Preparing template
 ✔ Installing package dependencies
 ✔ Created new application app.aragonpm.eth in app

 ~/code/aragon $ cd app
 ~/code/aragon/app $ aragon run --kit Kit --kit-init @ARAGON_ENS
 ✔ Start a local Ethereum network
 ✔ Check IPFS
 ✔ Publish app to APM
 ✔ Deploy Kit
 ❯ Create DAO
   ✖ Create new DAO from kit
     → Returned error: VM Exception while processing transaction: revert
     Checking DAO
   Open DAO
 ✖ Returned error: VM Exception while processing transaction: revert
```

**Comment by kernelwhisperer** [comment]
Temporary fix, please confirm if it works:
```
aragon init app react-kit
cd app
npm i -D @aragon/cli@5.2.0
npm i -D ganache-core@2.2.1
npm run start:aragon:ipfs:kit
```

Most likely this is because:
> christopher.dixon 10:45 AM
@gabi so it seems dao.newAppInstance is working but it fails at .initializing on both the token manager and voting app. .initialize on the counter is unaffected
ok so i may be remembering wrong, but has the token manager been redone recently? im pretty sure this isnt the same version i was looking at a few days back

With the release of `5.2.1` , `aragen` was upgraded from `2.0.0-beta.1` to `2.0.3`, which I assume contains the latest versions of the token-manager and voting which are breaking this kit.

Also, `ganache-core` needs to be pinned to `2.2.1` because of https://github.com/aragon/aragon-cli/issues/274

May be fixed by #15

**Comment by stan36** [comment]
this explains ALOT!

**Comment by stan36** [comment]
no dice though... fails at same spot but with a new string of errors:

 ✖ Returned error: VM Exception while processing transaction: revert

npm ERR! Linux 4.15.0-42-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start:aragon:ipfs" "--" "--kit" "Kit" "--kit-init" "@ARAGON_ENS"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! app-name@1.0.0 start:aragon:ipfs: `aragon run "--kit" "Kit" "--kit-init" "@ARAGON_ENS"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app-name@1.0.0 start:aragon:ipfs script 'aragon run "--kit" "Kit" "--kit-init" "@ARAGON_ENS"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app-name package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     aragon run "--kit" "Kit" "--kit-init" "@ARAGON_ENS"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app-name
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app-name
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/stan36/repos/freshDAO/app/npm-debug.log

npm ERR! Linux 4.15.0-42-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start:aragon:ipfs:kit"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! app-name@1.0.0 start:aragon:ipfs:kit: `npm run start:aragon:ipfs -- --kit Kit --kit-init @ARAGON_ENS`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app-name@1.0.0 start:aragon:ipfs:kit script 'npm run start:aragon:ipfs -- --kit Kit --kit-init @ARAGON_ENS'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app-name package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run start:aragon:ipfs -- --kit Kit --kit-init @ARAGON_ENS
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app-name
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app-name
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/stan36/repos/freshDAO/app/npm-debug.log

**Comment by stan36** [comment]
rm -rf ~/.aragon/ganache-db-8545/
fixes the above error if encountered

**Comment by sohkai** [comment]
Hmm, I think we have the updated dependencies for the voting and token manager, and we haven't changed their initialization interfaces. It'd be still good to update them though.

**Comment by proofoftom** [comment]
The workaround does seem to work. As far as this issue being closed though without a workaround: I'm still hitting the same issue unfortunately 🙁
```shell
 ~/code/aragon $ aragon init app react-kit
 ✔ Preparing initialization
 ✔ Cloning app template
 ✔ Preparing template
 ✔ Installing package dependencies
 ✔ Created new application app.aragonpm.eth in app
 ~/code/aragon $ cd app
 ~/code/aragon/app $ aragon run --kit Kit --kit-init @ARAGON_ENS
 ✔ Start a local Ethereum network
 ✔ Check IPFS
 ✔ Publish app to APM
 ✔ Deploy Kit
 ❯ Create DAO
   ✖ Create new DAO from kit
     → Returned error: VM Exception while processing transaction: revert
     Checking DAO
   Open DAO
 ✖ Returned error: VM Exception while processing transaction: revert
```

**Comment by 0xGabi** [comment]
Hi @tommycox I suspect it could be posible that you don't have last version of aragonCLI (v5.2.2)

I tested yesterday before merge the new boilerplate and I just check again with a fresh environment and it's working for me. 

This are the steps I followed: 
```
rm -rf ~/.aragon
npm i -g @aragon/cli
aragon init app react-kit
cd app
aragon run --kit Kit --kit-init @ARAGON_ENS
``` 

Could you try again, thanks

**Comment by proofoftom** [comment]
Woohoo! I suspect I also forgot to delete `~/.aragon`. Thanks much @galactusss

**Comment by cslarson** [comment]
I think this problem may have cropped up again. I've deleted `~/.aragon` and reinstalled `@aragon/cli` (currently version `5.3.3`).
