### ISSUE TITLE
npm run start:local 'scripts' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by manmountain** [aragon/aragon-react-kit-boilerplate#24]
Im installing a fresh kit with the following (Im on win10)

>rmdir /Q /S C:\Users\goran\.aragon

>node --version
v8.11.3

>npm --version
6.4.1

>npm i -g @aragon/cli
...
+ @aragon/cli@5.2.2
added 1636 packages from 1356 contributors in 230.073s

>npm list -g @aragon/cli
C:\Users\goran\AppData\Roaming\npm
`-- @aragon/cli@5.2.2

>aragon --version
5.2.2

>aragon init app react-kit
√ Preparing initialization
√ Cloning app template
√ Preparing template
√ Installing package dependencies
√ Created new application app.aragonpm.eth in app

>cd app

>aragon run --kit Kit --kit-init @ARAGON_ENS
 √ Start a local Ethereum network
 √ Check IPFS
 √ Publish app to APM
 √ Deploy Kit
 √ Create DAO
 √ Open DAO
 i You are now ready to open your app in Aragon.
 i Here are some Ethereum accounts you can use.
  The first one will be used for all the actions the CLI performs.
  You can use your favorite Ethereum provider or wallet to import their private keys.

Address #1:  0xb4124cEB3451635DAcedd11767f004d8a28c6eE7 (this account is used to deploy DAOs, it has more permissions)
Private key: a8a54b2d8197bc0b19bb8a084031be71835580a01e70a45a13babd16c9bc1563
Address #2:  0x8401Eb5ff34cc943f096A32EF3d5113FEbE8D4Eb
Private key: ce8e3bda3b44269c147747a373646393b1504bfcbb73fc9564f5d753d8116608
 i The accounts were generated from the following mnemonic phrase:
explain tackle mirror kit van hammer degree position ginger unfair soup bonus

 i This is the configuration for your development deployment:
    Ethereum Node: ws://localhost:8545
    ENS registry: 0x5f6f7e8cc7346a11ca2def8f827b7a0b612c56a1
    APM registry: aragonpm.eth
    DAO address: 0x5b6a3301a67A4bfda9D3a528CaD34cac6e7F8070

    Opening http://localhost:3000/#/0x5b6a3301a67A4bfda9D3a528CaD34cac6e7F8070 to view your DAO
(node:13984) UnhandledPromiseRejectionWarning: Error: Error: Command failed: npm run start:local
'scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aragon@0.6.0 start:local: `scripts/launch-local.sh`
npm ERR! Exit status 1

I attached the complete log
[2019-01-07T11_34_30_014Z-debug.log](https://github.com/aragon/aragon-react-kit-boilerplate/files/2732588/2019-01-07T11_34_30_014Z-debug.log)

**Comment by manmountain** [comment]
Im adding the package.json generated in the app dir. No start:local script is defined in scripts.
[package.txt](https://github.com/aragon/aragon-react-kit-boilerplate/files/2732851/package.txt)

**Comment by sohkai** [comment]
Ah yes, this will be fixed by https://github.com/aragon/aragon/pull/557.
