### ISSUE TITLE
Upgrade dependencies and scripts

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-react-kit-boilerplate#9]
In particular, upgrade:

- `@aragon/cli`
- `@aragon/ui` and its copy script
- `@aragon/os`
- `truffle`
- Add `@aragon/react-helpers`

**Comment by izqui** [comment]
`truffle` is no longer required, as it can be used from the cli

**Comment by sohkai** [comment]
Mmmm I think that'd be really confusing to not have truffle.
